import { Fragment, useEffect, useState, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { FileMentionPill } from "../../../elements/FileMention";
import { classNames } from "../../../elements/utils";

export interface ImageBlockProps { readonly src: string; readonly alt?: string; readonly caption?: string; readonly maxHeight?: number; readonly thumbnail?: boolean; readonly className?: string }
export function ImageLightbox({ src, alt = "", onClose }: { readonly src: string; readonly alt?: string; readonly onClose: () => void }) { useEffect(() => { const key = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; addEventListener("keydown", key); return () => removeEventListener("keydown", key); }, [onClose]); if (typeof document === "undefined") return null; return createPortal(<div className="fraym-image-lightbox" data-slot="image-lightbox" onClick={onClose} role="presentation"><button aria-label="Close image" onClick={onClose} type="button">×</button><img alt={alt} onClick={(event) => event.stopPropagation()} src={src} /></div>, document.body); }
export function ImageBlock({ src, alt = "", caption, maxHeight = 320, thumbnail = false, className }: ImageBlockProps) { const [open, setOpen] = useState(false); return <figure className={classNames("fraym-image-block", thumbnail && "is-thumbnail", className)} data-slot="image-block"><button aria-label={alt || "Open image"} onClick={() => setOpen(true)} type="button"><img alt={alt} loading="lazy" src={src} style={{ maxHeight: thumbnail ? 96 : maxHeight, maxWidth: thumbnail ? 96 : undefined }} /></button>{caption ? <figcaption>{caption}</figcaption> : null}{open ? <ImageLightbox alt={alt} onClose={() => setOpen(false)} src={src} /> : null}</figure>; }
export function ImageRefPill({ number }: { readonly number: number }) { return <span className="fraym-image-reference">▧ Image {number}</span>; }
export interface UserImageAttachment { readonly src: string }
export function UserImageAttachments({ images }: { readonly images: readonly UserImageAttachment[] }) { return images.length ? <div className="fraym-user-images"><UserImageThumbnails images={images} /><div>{images.map((_, index) => <ImageRefPill key={index} number={index + 1} />)}</div></div> : null; }
export function UserImageThumbnails({ images }: { readonly images: readonly UserImageAttachment[] }) { return images.length ? <div className="fraym-user-images__thumbnails">{images.map((image, index) => <ImageBlock alt={`Image ${index + 1}`} key={`${image.src}-${index}`} src={image.src} thumbnail />)}</div> : null; }
const marker = /\[Image #([1-9]\d*)(?:,[^\]\n]*)?\]/g;
export function renderTextWithImageMarkers(text: string, keyPrefix: string): ReactNode[] { const nodes: ReactNode[] = []; let cursor = 0; let index = 0; for (const match of text.matchAll(marker)) { if (match.index! > cursor) nodes.push(<Fragment key={`${keyPrefix}-text-${index}`}>{renderMentions(text.slice(cursor, match.index), `${keyPrefix}-${index}`)}</Fragment>); nodes.push(<ImageRefPill key={`${keyPrefix}-image-${index}`} number={Number(match[1])} />); cursor = match.index! + match[0].length; index += 1; } if (cursor < text.length) nodes.push(<Fragment key={`${keyPrefix}-tail`}>{renderMentions(text.slice(cursor), `${keyPrefix}-tail`)}</Fragment>); return nodes; }
function renderMentions(text: string, key: string): ReactNode { const parts = text.split(/(@[^\s]+)/g); return parts.map((part, index) => part.startsWith("@") ? <FileMentionPill fallback={part} key={`${key}-${index}`} path={part.slice(1)} /> : part); }
