import { useState, type ReactNode } from "react";
import { FileMentionPill } from "../../../elements/FileMention";
import { StreamingMarkdown } from "../../../elements/StreamingMarkdown";
import { classNames } from "../../../elements/utils";
import type { FraymDensity } from "../../surface-kit";

export interface ReasoningBlockProps { readonly text: string; readonly summary?: string | undefined; readonly defaultOpen?: boolean; readonly density?: FraymDensity; readonly live?: boolean; readonly className?: string }
export function ReasoningBlock({ text, summary = "Thinking", defaultOpen = false, density = "comfortable", live, className }: ReasoningBlockProps) { const [open, setOpen] = useState(defaultOpen); if (density === "compact") return <StreamingMarkdown className={classNames("fraym-reasoning-block is-compact", className)}>{text}</StreamingMarkdown>; return <section className={classNames("fraym-reasoning-block", live && "is-live", className)}><button aria-expanded={open} onClick={() => setOpen(!open)} type="button"><span>✦</span>{summary}<i aria-hidden="true">›</i></button>{open ? <StreamingMarkdown>{text}</StreamingMarkdown> : null}</section>; }
export interface NoticeCardProps { readonly level?: "info" | "warning" | "error"; readonly message: string; readonly source?: string; readonly className?: string }
export function NoticeCard({ level = "info", message, source, className }: NoticeCardProps) { return <aside className={classNames("fraym-notice-card", `fraym-notice-card--${level}`, className)}>{source ? <strong>{source}</strong> : null}<span>{message}</span></aside>; }
export interface RetryNoticeProps { readonly phase: "started" | "succeeded" | "failed" | "fallback"; readonly attempt?: number; readonly maxAttempts?: number; readonly fromModel?: string; readonly toModel?: string; readonly message?: string; readonly className?: string }
export function RetryNotice({ phase, attempt, maxAttempts, fromModel, toModel, message, className }: RetryNoticeProps) { const label = message ?? (phase === "fallback" ? `Falling back${fromModel && toModel ? ` ${fromModel} → ${toModel}` : ""}` : phase === "started" ? `Retrying${attempt ? ` (${attempt}${maxAttempts ? `/${maxAttempts}` : ""})` : ""}…` : phase === "succeeded" ? "Retry succeeded" : "Retry failed"); return <span className={classNames("fraym-retry-notice", `is-${phase}`, className)}><i aria-hidden="true" />{label}</span>; }
export interface FileMentionCardProps { readonly path: string; readonly detail?: string; readonly onOpen?: () => void; readonly className?: string }
export function FileMentionCard({ path, detail, onOpen, className }: FileMentionCardProps) { const content = <FileMentionPill fallback={path} path={path} {...(detail ? { label: detail } : {})} />; return onOpen ? <button className={className} onClick={onOpen} type="button">{content}</button> : <span className={className}>{content}</span>; }
export interface ChainOfThoughtGroupProps { readonly children: ReactNode; readonly count?: number; readonly label?: string; readonly defaultOpen?: boolean; readonly className?: string }
export function ChainOfThoughtGroup({ children, count, label = "Reasoning trace", defaultOpen = true, className }: ChainOfThoughtGroupProps) { const [open, setOpen] = useState(defaultOpen); return <section className={classNames("fraym-thought-group", className)}><button aria-expanded={open} onClick={() => setOpen(!open)} type="button">{label}{count === undefined ? null : ` (${count})`}<span aria-hidden="true">›</span></button>{open ? <div>{children}</div> : null}</section>; }
