import { type ReactNode, useCallback, useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { Scrim } from "../elements/Popover";
import { classNames } from "../elements/utils";
export const PHONE_WIDTH_QUERY = "(max-width: 760px)";
export function useIsPhoneWidth() { const [matches, setMatches] = useState(() => typeof window !== "undefined" && matchMedia(PHONE_WIDTH_QUERY).matches); useEffect(() => { const media = matchMedia(PHONE_WIDTH_QUERY); const change = () => setMatches(media.matches); change(); media.addEventListener("change", change); return () => media.removeEventListener("change", change); }, []); return matches; }
export interface BottomSheetProps { readonly onClose: () => void; readonly title?: ReactNode; readonly children: ReactNode; readonly footer?: ReactNode; readonly className?: string; readonly ariaLabel?: string }
export function BottomSheet({ onClose, title, children, footer, className, ariaLabel }: BottomSheetProps) {
  const panel = useRef<HTMLDivElement | null>(null); const drag = useRef({ y: 0, time: 0, active: false }); const [leaving, setLeaving] = useState(false);
  const close = useCallback(() => { if (matchMedia("(prefers-reduced-motion: reduce)").matches) onClose(); else { setLeaving(true); setTimeout(onClose, 180); } }, [onClose]);
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.key === "Escape" && !event.isComposing) close(); }; addEventListener("keydown", key); return () => removeEventListener("keydown", key); }, [close]);
  if (typeof document === "undefined") return null;
  return createPortal(<><Scrim className="fraym-bottom-sheet__scrim" dim onClick={close} /><div aria-label={ariaLabel ?? (typeof title === "string" ? title : undefined)} aria-modal="true" className={classNames("fraym-bottom-sheet", leaving && "is-leaving", className)} data-slot="bottom-sheet" ref={panel} role="dialog"><div className="fraym-bottom-sheet__grab" data-slot="sheet-grab" onPointerDown={event => { drag.current = { y: event.clientY, time: event.timeStamp, active: true }; event.currentTarget.setPointerCapture(event.pointerId); }} onPointerMove={event => { if (!drag.current.active || !panel.current) return; panel.current.style.transform = `translateY(${Math.max(0, event.clientY - drag.current.y)}px)`; }} onPointerUp={event => { if (!drag.current.active || !panel.current) return; drag.current.active = false; const distance = Math.max(0, event.clientY - drag.current.y); const velocity = distance / Math.max(1, event.timeStamp - drag.current.time); if (distance > panel.current.offsetHeight * .33 || velocity > .55) close(); else panel.current.style.transform = ""; }}><span aria-hidden="true" />{title != null ? <div>{title}</div> : null}</div><div className="fraym-bottom-sheet__body" data-slot="sheet-body">{children}</div>{footer != null ? <div className="fraym-bottom-sheet__footer" data-slot="sheet-footer">{footer}</div> : null}</div></>, document.body);
}
