import { createContext, type ComponentProps, type ReactNode, useContext, useEffect, useId, useRef, useState } from "react";
import { classNames } from "../elements/utils";
interface MenuBarValue { openId: string | null; setOpenId(id: string | null): void }
const MenuBarContext = createContext<MenuBarValue | null>(null);
export interface MenuBarProps extends ComponentProps<"div"> {}
export function MenuBar({ className, children, ...props }: MenuBarProps) { const [openId, setOpenId] = useState<string | null>(null); const root = useRef<HTMLDivElement | null>(null); useEffect(() => { if (!openId) return; const pointer = (event: PointerEvent) => { if (!root.current?.contains(event.target as Node)) setOpenId(null); }; const key = (event: KeyboardEvent) => { if (event.key === "Escape") setOpenId(null); }; addEventListener("pointerdown", pointer, true); addEventListener("keydown", key); return () => { removeEventListener("pointerdown", pointer, true); removeEventListener("keydown", key); }; }, [openId]); return <MenuBarContext.Provider value={{ openId, setOpenId }}><div className={classNames("fraym-menubar", className)} data-slot="menubar" ref={root} role="menubar" {...props}>{children}</div></MenuBarContext.Provider>; }
export interface MenuProps { readonly id?: string; readonly label: ReactNode; readonly children: ReactNode; readonly triggerClassName?: string; readonly panelClassName?: string; readonly triggerProps?: ComponentProps<"button"> }
export function Menu({ id: provided, label, children, triggerClassName, panelClassName, triggerProps }: MenuProps) { const context = useContext(MenuBarContext); const generated = useId(); const id = provided ?? generated; const open = context?.openId === id; return <div className="fraym-menu" data-slot="menu"><button aria-expanded={open} aria-haspopup="menu" className={classNames("fraym-menu__trigger", triggerClassName)} data-slot="menu-trigger" role="menuitem" type="button" {...triggerProps} onClick={event => { triggerProps?.onClick?.(event); context?.setOpenId(open ? null : id); }}>{label}</button>{open ? <div className={classNames("fraym-menu__panel", panelClassName)} data-slot="menu-panel" role="menu">{children}</div> : null}</div>; }
export interface MenuItemProps extends ComponentProps<"button"> { readonly icon?: ReactNode; readonly closeOnSelect?: boolean }
export function MenuItem({ icon, closeOnSelect = true, className, onClick, children, ...props }: MenuItemProps) { const context = useContext(MenuBarContext); return <button className={classNames("fraym-menu__item", className)} data-slot="menu-item" onClick={event => { onClick?.(event); if (closeOnSelect) context?.setOpenId(null); }} role="menuitem" type="button" {...props}>{icon ? <span>{icon}</span> : null}{children}</button>; }
