import { useMemo, useState } from "react";
import { createPortal } from "react-dom";
import type { Placement } from "../elements/Popover";
import { popoverStyle } from "../elements/Popover";
import { classNames } from "../elements/utils";
import { BottomSheet, useIsPhoneWidth } from "./bottom-sheet";
import { InputGroup } from "./input-group";
export interface SelectorMenuCategory<TItem> { readonly id: string; readonly label: string; readonly items: readonly TItem[]; readonly providerId?: string }
export interface SelectorMenuProps<TItem> { readonly categories: readonly SelectorMenuCategory<TItem>[]; readonly selectedId: string; readonly getItemId: (item: TItem) => string; readonly query: string; readonly onQueryChange: (query: string) => void; readonly searchPlaceholder?: string; readonly filter?: (items: readonly TItem[], query: string) => readonly TItem[]; readonly renderItem: (item: TItem, selected: boolean, onPick: () => void) => React.ReactNode; readonly renderCategoryIcon?: (category: SelectorMenuCategory<TItem>) => React.ReactNode; readonly renderCategoryLabel?: (category: SelectorMenuCategory<TItem>) => React.ReactNode; readonly renderFlyoutHeader?: (category: SelectorMenuCategory<TItem>) => React.ReactNode; readonly beforeCategories?: React.ReactNode; readonly footer?: React.ReactNode; readonly anchorRect?: DOMRect | null; readonly place?: Placement; readonly style?: React.CSSProperties; readonly className?: string; readonly onPick: (item: TItem) => void; readonly onClose: () => void; readonly panelWidth?: number; readonly searchWidth?: number; readonly flyoutWidth?: number; readonly sheetTitle?: string }
function uniqueItems<T>(categories: readonly SelectorMenuCategory<T>[], id: (item: T) => string) { const seen = new Set<string>(); return categories.flatMap(category => category.items).filter(item => { const key = id(item); if (seen.has(key)) return false; seen.add(key); return true; }); }
export function SelectorMenu<TItem>(props: SelectorMenuProps<TItem>) {
  const { categories, selectedId, getItemId, query, onQueryChange, filter, renderItem, onPick, onClose, renderCategoryIcon, renderCategoryLabel, renderFlyoutHeader, beforeCategories, footer, panelWidth = 300, searchWidth = 320, flyoutWidth = 290 } = props;
  const [categoryId, setCategoryId] = useState<string | null>(null); const phone = useIsPhoneWidth(); const searching = Boolean(query.trim());
  const items = useMemo(() => uniqueItems(categories, getItemId), [categories, getItemId]); const hits = searching ? (filter ? filter(items, query) : items.filter(item => getItemId(item).toLowerCase().includes(query.trim().toLowerCase()))) : [];
  const category = categoryId ? categories.find(item => item.id === categoryId) ?? null : null;
  const rows = (list: readonly TItem[]) => list.map(item => <div key={getItemId(item)}>{renderItem(item, getItemId(item) === selectedId, () => onPick(item))}</div>);
  const content = <><InputGroup aria-label={props.searchPlaceholder ?? "Search"} autoFocus={!phone} leading="⌕" placeholder={props.searchPlaceholder ?? "Search…"} value={query} variant="ghost" onChange={event => onQueryChange(event.currentTarget.value)} />{searching ? <div className="fraym-selector-menu__rows">{hits.length ? rows(hits) : <div className="fraym-selector-menu__empty">No results match "{query.trim()}".</div>}</div> : category && phone ? <div className="fraym-selector-menu__rows"><button className="fraym-selector-menu__back" onClick={() => setCategoryId(null)} type="button">‹ {renderCategoryLabel ? renderCategoryLabel(category) : category.label}</button>{renderFlyoutHeader?.(category)}{rows(category.items)}</div> : <div className="fraym-selector-menu__rows">{beforeCategories}{categories.map(item => <button className="fraym-selector-menu__category" data-category-id={item.id} data-slot="selector-category-row" key={item.id} onClick={() => setCategoryId(item.id)} onMouseEnter={() => !phone && setCategoryId(item.id)} type="button">{renderCategoryIcon?.(item)}<span>{renderCategoryLabel ? renderCategoryLabel(item) : item.label}</span>{item.items.some(candidate => getItemId(candidate) === selectedId) ? <i /> : null}<small>{item.items.length}</small><span>›</span></button>)}</div>}</>;
  if (phone) return <BottomSheet ariaLabel={props.sheetTitle ?? "Choose"} footer={footer} onClose={onClose} title={props.sheetTitle}>{content}</BottomSheet>;
  if (typeof document === "undefined") return null;
  const width = searching ? searchWidth : panelWidth; const positioned = props.anchorRect ? popoverStyle(props.anchorRect, props.place ?? "above-right", width) : props.style;
  return createPortal(<><div className="fraym-selector-menu__scrim" onClick={onClose} /><div className={classNames("fraym-selector-menu", props.className)} data-slot="selector-menu" style={{ width, ...positioned }}>{content}{footer}{category && !searching ? <div className="fraym-selector-menu__flyout" data-slot="selector-flyout" style={{ width: flyoutWidth }}>{renderFlyoutHeader?.(category)}{rows(category.items)}</div> : null}</div></>, document.body);
}
