export const tokens = {
  color: {
    primary: "var(--fraym-color-primary)",
    primaryStrong: "var(--fraym-color-primary-strong)",
    onPrimary: "var(--fraym-color-on-primary)",
    bg: "var(--fraym-color-bg)",
    rail: "var(--fraym-color-rail)",
    surface: "var(--fraym-color-surface)",
    surface2: "var(--fraym-color-surface-2)",
    surface3: "var(--fraym-color-surface-3)",
    border: "var(--fraym-color-border)",
    borderSoft: "var(--fraym-color-border-soft)",
    text: "var(--fraym-color-text)",
    text2: "var(--fraym-color-text-2)",
    text3: "var(--fraym-color-text-3)",
    muted: "var(--fraym-color-muted)",
    accent: "var(--fraym-color-accent)",
    success: "var(--fraym-color-success)",
    danger: "var(--fraym-color-danger)",
    warning: "var(--fraym-color-warning)",
    info: "var(--fraym-color-info)",
    iris: "var(--fraym-color-iris)",
  },
  type: {
    family: "var(--fraym-font-sans)",
    monoFamily: "var(--fraym-font-mono)",
    display: "var(--fraym-type-display)",
    headingXl: "var(--fraym-type-heading-xl)",
    headingLg: "var(--fraym-type-heading-lg)",
    title: "var(--fraym-type-title)",
    bodyMd: "var(--fraym-type-body-md)",
    bodySm: "var(--fraym-type-body-sm)",
    label: "var(--fraym-type-label)",
    code: "var(--fraym-type-code)",
    caption: "var(--fraym-type-caption)",
    eyebrow: "var(--fraym-type-eyebrow)",
    xs: "var(--fraym-type-xs)",
    sm: "var(--fraym-type-sm)",
    base: "var(--fraym-type-base)",
    lg: "var(--fraym-type-lg)",
    xl: "var(--fraym-type-xl)",
  },
  space: {
    xs: "var(--fraym-space-xs)",
    sm: "var(--fraym-space-sm)",
    md: "var(--fraym-space-md)",
    lg: "var(--fraym-space-lg)",
    xl: "var(--fraym-space-xl)",
    beat: "var(--fraym-space-beat)",
    trace: "var(--fraym-space-trace)",
    turn: "var(--fraym-space-turn)",
    1: "var(--fraym-space-1)",
    2: "var(--fraym-space-2)",
    3: "var(--fraym-space-3)",
    4: "var(--fraym-space-4)",
    5: "var(--fraym-space-5)",
    6: "var(--fraym-space-6)",
    8: "var(--fraym-space-8)",
    10: "var(--fraym-space-10)",
  },
  layout: {
    railWidth: "var(--fraym-rail-width)",
    dockWidth: "var(--fraym-dock-width)",
  },
  radius: {
    sm: "var(--fraym-radius-sm)",
    md: "var(--fraym-radius-md)",
    lg: "var(--fraym-radius-lg)",
    xl: "var(--fraym-radius-xl)",
    full: "var(--fraym-radius-full)",
  },
  motion: {
    fast: "var(--fraym-motion-fast)",
    normal: "var(--fraym-motion-normal)",
    slow: "var(--fraym-motion-slow)",
  },
} as const;

export type FraymTokens = typeof tokens;
export type FraymColorToken = keyof FraymTokens["color"];
