import { createPortal } from "react-dom"; import type { ContextBreakdown, UsageStatus } from "@fraym/driver"; import { type Placement, PopoverPanel, Scrim } from "../../elements/Popover"; import { Meter } from "../density-ui"; import { classNames } from "../../elements/utils";
export type ContextRowTone = "accent" | "warn" | "blue" | "add" | "mute";
export interface ContextRow { readonly name: string; readonly k: number; readonly pct: number; readonly free?: boolean; readonly tone?: ContextRowTone }
export interface PlanLimit { readonly name: string; readonly pct: number; readonly resets: string; readonly status?: UsageStatus }
export interface ContextPopoverProps { readonly used: number; readonly max: number; readonly breakdown: readonly ContextRow[]; readonly planLimits?: readonly PlanLimit[]; readonly onClose: () => void; readonly anchorRect?: DOMRect | null; readonly place?: Placement; readonly style?: React.CSSProperties; readonly className?: string }
export function ContextBreakdownView({ used, max, breakdown, planLimits = [], className }: Omit<ContextPopoverProps, "onClose" | "anchorRect" | "place" | "style">) { const percent = max > 0 ? Math.round((used / max) * 100) : 0; return <section className={classNames("fraym-context-breakdown", className)}><header><span>Context window</span><strong>{used.toLocaleString()} / {max.toLocaleString()}</strong><small>{percent}% used</small></header><Meter total={max} value={used} /><dl>{breakdown.map((row) => <div key={row.name}><dt><i className={`fraym-tone-dot--${row.tone ?? "mute"}`} />{row.name}</dt><dd>{row.free ? "free" : `${row.k.toLocaleString()}k`}<span>{row.pct}%</span></dd></div>)}</dl>{planLimits.length ? <div className="fraym-context-breakdown__limits">{planLimits.map((limit) => <div key={limit.name}><span>{limit.name}</span><strong>{limit.pct}%</strong><small>{limit.resets}</small><Meter tone={limit.status === "critical" || limit.status === "exhausted" ? "warn" : "accent"} total={100} value={limit.pct} /></div>)}</div> : null}</section>; }
export function ContextPopover({ onClose, anchorRect, place = "above", style, ...props }: ContextPopoverProps) { if (typeof document === "undefined") return null; const panelProps = { className: "fraym-context-popover", place, width: 300, ...(anchorRect === undefined ? {} : { anchorRect }), ...(style === undefined ? {} : { style }) }; return createPortal(<><Scrim onClick={onClose} /><PopoverPanel {...panelProps}><ContextBreakdownView {...props} /></PopoverPanel></>, document.body); }
export function contextBreakdownToRows(breakdown: ContextBreakdown): readonly ContextRow[] { const max = breakdown.max || 1; let index = 0; return Object.entries(breakdown).flatMap(([name, value]) => { if (["used", "max", "remaining"].includes(name) || typeof value !== "number" || value <= 0) return []; const row = { name: name.replace(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase()), k: Math.round(value / 100) / 10, pct: Math.round((value / max) * 100), tone: (["accent", "blue", "add", "warn"] as const)[index % 4] ?? "accent" }; index += 1; return [row]; }); }
export function contextBreakdownHeader(breakdown: ContextBreakdown) { return { used: breakdown.used, max: breakdown.max }; }
export function contextBreakdownPercent(breakdown: ContextBreakdown) { return breakdown.max > 0 ? Math.min(100, Math.max(0, Math.round((breakdown.used / breakdown.max) * 100))) : 0; }
