import { useMemo, useState } from "react"; import type { HostUiRequest, HostUiResponse, HostUiSelectOption } from "@fraym/driver"; import { Button } from "../../elements/button"; import { Checkbox } from "../../elements/checkbox"; import { Input } from "../../elements/input"; import { Radio } from "../../elements/radio"; import { classNames } from "../../elements/utils"; import { AskFieldControl, readDialogField } from "./ask-field-control";
export type SelectHostUiRequest = Omit<HostUiRequest, "kind" | "title" | "options"> & { readonly kind: "select"; readonly title: string; readonly options: readonly (string | HostUiSelectOption)[] };
export type InputHostUiRequest = Omit<HostUiRequest, "kind" | "title"> & { readonly kind: "input"; readonly title: string };
const label = (option: string | HostUiSelectOption) => typeof option === "string" ? option : option.label;
export function hostUiInstanceKey(request: HostUiRequest): string { return request.kind === "select" && request.selectionMarker === "checkbox" ? `select-multi\0${request.title}\0${request.options?.map((option) => typeof option === "string" ? option : "label" in option ? option.label : option.name).join("\0")}` : request.requestId ?? request.id; }
export interface SelectRequestPickerProps { readonly request: SelectHostUiRequest; readonly onRespond: (response: HostUiResponse) => void; readonly className?: string }
export function SelectRequestPicker({ request, onRespond, className }: SelectRequestPickerProps) { const requestId = request.requestId ?? request.id; const field = readDialogField(request.meta); if (field?.type === "toggle") return <AskFieldControl {...(className ? { className } : {})} field={field} onCancel={() => onRespond({ requestId, cancelled: true })} onSubmit={(value) => onRespond({ requestId, value })} question={request.title} toggleSubmit={{ on: label(request.options[0] ?? "Yes"), off: label(request.options[1] ?? "No") }} />; return <SelectOptions request={request} onRespond={onRespond} {...(className ? { className } : {})} />; }
function SelectOptions({ request, onRespond, className }: SelectRequestPickerProps) { const requestId = request.requestId ?? request.id; const multiple = request.allowMultiple === true || request.selectionMarker === "checkbox"; const [checked, setChecked] = useState(() => new Set(request.checkedIndices ?? [])); const [other, setOther] = useState(""); const options = useMemo(() => request.options.map((option) => ({ label: label(option).replace(/ \(Recommended\)$/i, ""), ...(typeof option !== "string" && option.description ? { description: option.description } : {}), recommended: / \(Recommended\)$/i.test(label(option)), other: /^(other|other \(type your own\))$/i.test(label(option)) })), [request.options]); const toggle = (index: number) => setChecked((current) => { const next = new Set(current); if (next.has(index)) next.delete(index); else next.add(index); return next; }); const submit = () => onRespond({ requestId, values: options.filter((_, index) => checked.has(index)).map((option) => option.label) }); return <section className={classNames("fraym-select-request", className)}><header><span>Question</span><strong>{request.title}</strong></header><div role={multiple ? "group" : "radiogroup"}>{options.map((option, index) => option.other ? <form key={index} onSubmit={(event) => { event.preventDefault(); onRespond({ requestId, value: other }); }}><Input aria-label="Other answer" onChange={(event) => setOther(event.currentTarget.value)} placeholder="Type your own answer" value={other} /><Button disabled={!other.trim()} size="sm" type="submit">Submit</Button></form> : <label className="fraym-select-request__option" key={index}>{multiple ? <Checkbox checked={checked.has(index)} onCheckedChange={() => toggle(index)} /> : <Radio checked={request.initialIndex === index} name={requestId} onCheckedChange={() => onRespond({ requestId, value: label(request.options[index]!) })} value={option.label} />}<span><strong>{option.label}{option.recommended ? <small>Recommended</small> : null}</strong>{option.description ? <small>{option.description}</small> : null}</span></label>)}</div><footer><Button onClick={() => onRespond({ requestId, cancelled: true })} size="sm" variant="ghost">Cancel</Button>{multiple ? <Button disabled={!checked.size} onClick={submit} size="sm" variant="default">Continue</Button> : null}</footer></section>; }
export type ConfirmHostUiRequest = Omit<HostUiRequest, "kind" | "title"> & { readonly kind: "confirm"; readonly title: string };
export interface ConfirmRequestPickerProps { readonly request: ConfirmHostUiRequest; readonly onRespond: (response: HostUiResponse) => void; readonly className?: string }
export function ConfirmRequestPicker({ request, onRespond, className }: ConfirmRequestPickerProps) { const requestId = request.requestId ?? request.id; return <section className={classNames("fraym-confirm-request", className)}><strong>{request.message || request.title}</strong><footer><Button onClick={() => onRespond({ requestId, confirmed: false })} variant="ghost">Cancel</Button><Button onClick={() => onRespond({ requestId, confirmed: true })} variant="default">Confirm</Button></footer></section>; }
export interface InputRequestCardProps { readonly request: InputHostUiRequest; readonly onRespond: (response: HostUiResponse) => void; readonly className?: string }
export function InputRequestCard({ request, onRespond, className }: InputRequestCardProps) { const requestId = request.requestId ?? request.id; const field = readDialogField(request.meta) ?? { type: "text" as const, ...(request.placeholder ? { placeholder: request.placeholder } : {}) }; return <AskFieldControl {...(className ? { className } : {})} field={field} {...(request.initialValue ? { initialValue: request.initialValue } : {})} onCancel={() => onRespond({ requestId, cancelled: true })} onSubmit={(value) => onRespond({ requestId, value })} question={request.title} />; }
