import { useEffect, useImperativeHandle, useRef, type ClipboardEvent, type KeyboardEvent, type Ref } from "react"; import { classNames } from "../../elements/utils";
export interface MentionPillData { readonly value: string; readonly label: string; readonly path: string; readonly isDirectory: boolean }
export interface ImagePillData { readonly id: string; readonly number: number }
export interface PositionedImagePillData extends ImagePillData { readonly offset: number }
export interface MentionEditorHandle { insertMention(pill: MentionPillData): void; insertImagePill(pill: ImagePillData): void; imagePillOffsets(): { readonly id: string; readonly offset: number }[]; removeImagePill(id: string): void; syncImagePillLabels(orderedIds: readonly string[]): void; insertText(text: string): void; focus(): void }
export interface MentionEditorProps { readonly value: string; readonly imagePills?: readonly PositionedImagePillData[]; readonly placeholder?: string; readonly disabled?: boolean; readonly className?: string; readonly onChange: (value: string, caret: number, imagePills: readonly { readonly id: string; readonly offset: number }[]) => void; readonly onCaretChange: (caret: number) => void; readonly onKeyDown?: (event: KeyboardEvent<HTMLDivElement>) => void; readonly onPaste?: (event: ClipboardEvent<HTMLDivElement>) => void; readonly handleRef?: Ref<MentionEditorHandle>; readonly onImagePillRemoved?: (id: string) => void }
function nodeText(node: Node): string { if (node.nodeType === Node.TEXT_NODE) return node.textContent ?? ""; if (node instanceof HTMLElement && node.dataset.imagePill !== undefined) return ""; if (node instanceof HTMLElement && node.dataset.mention !== undefined) return node.dataset.value ?? ""; return node.nodeName === "BR" ? "\n" : node.textContent ?? ""; }
export function serializeEditor(root: HTMLElement): string { return [...root.childNodes].map(nodeText).join(""); }
export function imagePillOffsets(root: HTMLElement) { const output: { id: string; offset: number }[] = []; let offset = 0; for (const child of [...root.childNodes]) { if (child instanceof HTMLElement && child.dataset.imagePill !== undefined && child.dataset.imageId) output.push({ id: child.dataset.imageId, offset }); offset += nodeText(child).length; } return output; }
export function editorCaretOffset(root: HTMLElement, selection: Selection | null): number | null { if (!selection?.rangeCount || !selection.anchorNode || !root.contains(selection.anchorNode)) return null; const range = selection.getRangeAt(0).cloneRange(); range.selectNodeContents(root); range.setEnd(selection.anchorNode, selection.anchorOffset); return range.toString().length; }
export function setCaret(root: HTMLElement, target: number): void { const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT); let remaining = target; let node = walker.nextNode(); while (node) { const length = node.textContent?.length ?? 0; if (remaining <= length) { const range = document.createRange(); range.setStart(node, remaining); range.collapse(true); const selection = getSelection(); selection?.removeAllRanges(); selection?.addRange(range); return; } remaining -= length; node = walker.nextNode(); } root.focus(); }
function pill(value: string, label: string, attrs: Record<string, string>) { const span = document.createElement("span"); span.contentEditable = "false"; span.className = "fraym-mention-pill"; span.textContent = label; span.dataset.value = value; Object.entries(attrs).forEach(([key, item]) => span.dataset[key] = item); return span; }
export function MentionEditor({ value, placeholder, disabled, className, onChange, onCaretChange, onKeyDown, onPaste, handleRef }: MentionEditorProps) { const root = useRef<HTMLDivElement>(null); const notify = () => { if (!root.current) return; const caret = editorCaretOffset(root.current, getSelection()) ?? serializeEditor(root.current).length; onChange(serializeEditor(root.current), caret, imagePillOffsets(root.current)); onCaretChange(caret); }; useEffect(() => { if (root.current && serializeEditor(root.current) !== value) root.current.textContent = value; }, [value]); useImperativeHandle(handleRef, () => ({ insertMention(data) { if (!root.current) return; root.current.append(pill(data.value, data.label, { mention: "" }), document.createTextNode(" ")); notify(); }, insertImagePill(data) { if (!root.current) return; root.current.append(pill("", `▧ Image ${data.number}`, { imagePill: "", imageId: data.id })); notify(); }, imagePillOffsets: () => root.current ? imagePillOffsets(root.current) : [], removeImagePill(id) { root.current?.querySelector(`[data-image-id="${CSS.escape(id)}"]`)?.remove(); notify(); }, syncImagePillLabels(ids) { ids.forEach((id, index) => { const node = root.current?.querySelector(`[data-image-id="${CSS.escape(id)}"]`); if (node) node.textContent = `▧ Image ${index + 1}`; }); }, insertText(text) { root.current?.append(document.createTextNode(text)); notify(); }, focus: () => root.current?.focus() })); return <div aria-disabled={disabled} aria-label={placeholder ?? "Message"} className={classNames("fraym-mention-editor", className)} contentEditable={!disabled} data-placeholder={placeholder} data-slot="mention-editor" onInput={notify} onKeyDown={onKeyDown} onKeyUp={() => onCaretChange(editorCaretOffset(root.current!, getSelection()) ?? 0)} onPaste={onPaste} ref={root} role="textbox" suppressContentEditableWarning tabIndex={disabled ? -1 : 0} />; }
