import { createContext, useContext, useMemo } from "react"; import { DEFAULT_SLASH_ENTRY_POLICY, type SlashEntryPolicy, type SlashIconName } from "../../registries/slash-entry-policy"; import { classNames } from "../../elements/utils";
export interface SlashEntryLayers { readonly plugin?: SlashEntryPolicy; readonly user?: SlashEntryPolicy }
const Context = createContext<SlashEntryLayers>({});
export function SlashEntryPolicyProvider({ layers, children }: { readonly layers: SlashEntryLayers; readonly children: React.ReactNode }) { return <Context.Provider value={layers}>{children}</Context.Provider>; }
export function useSlashEntryLayers() { return useContext(Context); }
export interface SlashEntryTarget { readonly kind?: string; readonly value?: string; readonly label?: string; readonly icon?: string }
export interface SlashEntrySpec { readonly icon?: string; readonly color?: string; readonly label?: string; readonly hidden?: boolean }
const fallback: Record<string, SlashIconName> = { command: "terminal", prompt: "chat", extension: "bolt", skill: "spark", file: "file", mention: "user", "command-arg": "arrowUpRight" };
export function slashKindIcon(kind: string | undefined): SlashIconName { return fallback[kind ?? ""] ?? "terminal"; }
function matchRule(pattern: string, value: string) { const regex = new RegExp(`^${pattern.split("*").map((part) => part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join(".*")}$`, "i"); return regex.test(value); }
function fromPolicy(policy: SlashEntryPolicy | undefined, key: string): SlashEntrySpec | null { if (!policy) return null; const exact = policy.exact[key]; if (exact) return { icon: exact }; const rule = policy.rules.find((item) => (Array.isArray(item.match) ? item.match : [item.match]).some((pattern) => matchRule(pattern, key))); return rule ? { icon: rule.icon } : null; }
export function resolveSlashEntrySpec(target: SlashEntryTarget, layers: SlashEntryLayers): SlashEntrySpec | null { const key = (target.value ?? target.label ?? "").replace(/^\//, "").toLowerCase(); if (!key) return null; return { ...(fromPolicy(DEFAULT_SLASH_ENTRY_POLICY, key) ?? {}), ...(target.icon ? { icon: target.icon } : {}), ...(fromPolicy(layers.plugin, key) ?? {}), ...(fromPolicy(layers.user, key) ?? {}) }; }
export function useSlashEntrySpec(target: SlashEntryTarget) { const layers = useSlashEntryLayers(); return useMemo(() => resolveSlashEntrySpec(target, layers), [layers, target.icon, target.kind, target.label, target.value]); }
export function SlashEntryGlyph({ spec, kind, size, className }: { readonly spec: SlashEntrySpec | null; readonly kind?: string; readonly size: number; readonly className?: string; readonly fallbackColor?: string }) { const icon = spec?.icon ?? slashKindIcon(kind); return /^(data:|https?:|\/)/.test(icon) ? <img alt="" className={className} height={size} src={icon} width={size} /> : <span aria-hidden="true" className={classNames("fraym-slash-glyph", className)} style={{ fontSize: size }}>{icon === "terminal" ? ">_" : icon === "spark" ? "✦" : icon === "file" ? "▤" : icon === "search" ? "⌕" : "◇"}</span>; }
