import { memo } from "react";
export interface UsageLimitView { readonly provider: string; readonly label: string; readonly usedPercent: number | null; readonly status: "ok" | "warning" | "critical" | "exhausted"; readonly scopeTier?: string; readonly inUse?: boolean; readonly resetsAt?: number }
const tiers = ["small", "medium", "large", "reasoning", "fast"];
export function selectProviderWarnings(all: readonly UsageLimitView[], provider: string | undefined, sessionActive: boolean): readonly UsageLimitView[] { return provider ? all.filter((item) => item.provider === provider) : sessionActive ? [] : all; }
export function modelTierFromId(id: string | undefined): string | undefined { const value = id?.toLowerCase(); return tiers.find((tier) => value?.includes(tier)); }
export function selectModelScopedWarnings(limits: readonly UsageLimitView[], modelId: string | undefined): readonly UsageLimitView[] { if (!modelId) return limits; const active = modelTierFromId(modelId); return limits.filter((limit) => !limit.scopeTier || !tiers.includes(limit.scopeTier) || limit.scopeTier === active); }
export function selectInUseLimits(limits: readonly UsageLimitView[]): readonly UsageLimitView[] { const active = limits.filter((limit) => limit.inUse); return active.length ? active : limits; }
export interface UsageLimitComposerSurfaceProps { readonly limits?: readonly UsageLimitView[]; readonly threshold?: number; readonly activeProvider?: string; readonly activeModelId?: string; readonly sessionActive?: boolean; readonly onDismiss?: () => void }
export const UsageLimitComposerSurface = memo(function UsageLimitComposerSurface({ limits = [], threshold = 80, activeProvider, activeModelId, sessionActive = false, onDismiss }: UsageLimitComposerSurfaceProps) { const warnings = selectModelScopedWarnings(selectProviderWarnings(selectInUseLimits(limits).filter((item) => item.status === "exhausted" || (item.usedPercent ?? 0) >= threshold), activeProvider, sessionActive), activeModelId); const worst = [...warnings].sort((a, b) => (b.usedPercent ?? 100) - (a.usedPercent ?? 100))[0]; if (!worst) return null; return <aside className="fraym-usage-limit" role="status"><span>◔</span><strong>{worst.provider} · {worst.label}</strong><span>{worst.usedPercent === null ? "limit reached" : `${worst.usedPercent.toFixed(1)}% used`}</span>{onDismiss ? <button aria-label="Dismiss usage warning" onClick={onDismiss} type="button">×</button> : null}</aside>; });
