import { useState, type ReactNode } from "react";
import { Badge } from "../../elements/Badge";
import { classNames } from "../../elements/utils";
import { useCommandTagResolver } from "../../registries/command-tag-registry";
import type { MessageBlockRendererMap } from "../../registries/message-block-registry";
import { resolveSurfaceRegistration, useSurfaceRendererMap } from "../../registries/surface-renderer-registry";
import { MessageDivider, MessageHeader, type MessageBlock, type MessageData } from "../message/message-core";
import { MessageBody } from "../message/messages/message-body";
import { UserImageThumbnails, renderTextWithImageMarkers } from "../message/messages/image-block";

const pasteMarker = /\[\[paste:(\d+)]]\n/g;
export type UserTextSegment = { readonly type: "text"; readonly text: string } | { readonly type: "paste"; readonly text: string };
export function splitUserPastedText(text: string): readonly UserTextSegment[] { const segments: UserTextSegment[] = []; let cursor = 0; for (const match of text.matchAll(pasteMarker)) { const length = Number(match[1]); const start = match.index! + match[0].length; const end = start + length; if (!Number.isSafeInteger(length) || length < 0 || end > text.length) continue; if (match.index! > cursor) segments.push({ type: "text", text: text.slice(cursor, match.index) }); segments.push({ type: "paste", text: text.slice(start, end) }); cursor = end; } if (cursor < text.length) segments.push({ type: "text", text: text.slice(cursor) }); return segments.length ? segments : [{ type: "text", text }]; }
export function splitLeadingUserCommand(blocks: readonly MessageBlock[]): { readonly label: string; readonly blocks: readonly MessageBlock[] } | null { const first = blocks[0]; if (first?.type !== "text") return null; const match = String(first.text ?? "").match(/^(\/[a-zA-Z][\w-]*(?::[\w-]+)?)(?:\s+|$)([\s\S]*)$/); if (!match) return null; const next = match[2] ? [{ ...first, text: match[2] }, ...blocks.slice(1)] : blocks.slice(1); return { label: match[1]!, blocks: next }; }
function PasteDisclosure({ text }: { readonly text: string }) { const [open, setOpen] = useState(false); return <section className="fraym-paste-disclosure"><button aria-expanded={open} onClick={() => setOpen(!open)} type="button"><span>{open ? "Pasted text" : text.slice(0, 160).replace(/\s+/g, " ") || "Pasted text"}</span><small>{text.length.toLocaleString()} chars</small><i aria-hidden="true">›</i></button>{open ? <pre>{text}</pre> : null}</section>; }
export interface ThreadMessageProps { readonly message: MessageData; readonly isLast?: boolean | undefined; readonly isStreaming?: boolean | undefined; readonly showHeader?: boolean; readonly showAvatar?: boolean; readonly components?: MessageBlockRendererMap | undefined; readonly className?: string }
export function ThreadMessage({ message, isLast, isStreaming, showHeader = true, showAvatar = true, components, className }: ThreadMessageProps) { const surfaceMap = useSurfaceRendererMap(); const resolveCommand = useCommandTagResolver(); if (message.role === "divider") return <MessageDivider message={message} />; if (message.customType) { const registration = resolveSurfaceRegistration(surfaceMap, `msg:${message.customType}`); return <>{registration.render({ channel: "message", customType: message.customType, payload: message.payload }, { respond: () => undefined })}</>; } if (message.role === "user") { const command = splitLeadingUserCommand(message.blocks); const blocks = command?.blocks ?? message.blocks; const images = blocks.filter((block) => block.type === "image" && typeof block.src === "string").map((block) => ({ src: String(block.src) })); return <article className={classNames("fraym-thread-message fraym-thread-message--user", className)}>{showHeader ? <MessageHeader messageRole="user" name={message.name ?? "You"} showAvatar={showAvatar} /> : null}<div className="fraym-thread-message__bubble">{images.length ? <UserImageThumbnails images={images} /> : null}{command ? <Badge tone="accent">{resolveCommand(command.label)?.label ?? command.label}</Badge> : null}{blocks.filter((block) => block.type === "text").flatMap((block, blockIndex) => splitUserPastedText(String(block.text ?? "")).map((segment, segmentIndex) => segment.type === "paste" ? <PasteDisclosure key={`${blockIndex}-${segmentIndex}`} text={segment.text} /> : <p key={`${blockIndex}-${segmentIndex}`}>{renderTextWithImageMarkers(segment.text, `${message.id ?? "message"}-${blockIndex}`)}</p>))}</div></article>; } return <article className={classNames("fraym-thread-message fraym-thread-message--agent", className)}>{showHeader ? <MessageHeader messageRole="agent" name={message.name ?? "Assistant"} meta={message.meta} showAvatar={showAvatar} /> : null}<MessageBody components={components} isLast={isLast} isStreaming={isStreaming} message={message} /></article>; }
